### ISSUE TITLE
Publish Single Node Offer

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#121]
Even though the single node offer has been largely supplanted by the existence of the VM images, it is still important to keep it up to date.  This commit applies these changes and others documented in the commit log.  https://github.com/wls-eng/arm-oraclelinux-wls/commit/0eb46ebf35a841e7f00bc411268276779a4304a9  

Because this repo has not yet had its default branch changed to `develop` I will attach the zip to this issue to upload to partner center.

**Comment by edburns** [comment]
[arm-oraclelinux-wls-1.0.17-arm-assembly.zip](https://github.com/wls-eng/arm-oraclelinux-wls/files/4852906/arm-oraclelinux-wls-1.0.17-arm-assembly.zip)

Publish this to partner center.

**Comment by jacobt123** [comment]
Published the new zip to Partner Center
