### ISSUE TITLE
Configured Cluster offer: provide option for automated Key Vault creation with uploaded SSL certificate

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#145]
Pre-release workshop and testing did not reveal this usability concern until too late for it to be included in the Q2 release.  After discussion with @m-reza-rahman today,  @edburns proposed this plan to address the issue without doing a full release.

The agreed upon level of user effort to enable App Gateway integration is the following.  

Before deploying the cluster offer the user must:

1. Create an Azure Key Vault.
1. Create a password protected signed SSL certificate in PFX format, either self-signed or authority signed.
1. Store the SSL certificate in the Key Vault
1. Store the password for the SSL certificate in the Key Vault.

We will upgrade the configured cluster offer to provide an option for the user to request the Key Vault be created dynamically on their behalf, and automatically populated with a certificate that is provided via file upload at the time of template deployment.

**Comment by edburns** [comment]
AB#1165828 User Story tracking this on Microsoft side.

**Comment by edburns** [comment]
See AB#1212676

**Comment by galiacheng** [comment]
Close the issue, as the PR has been merged.
