### ISSUE TITLE
Configured Cluster App Gateway Key Vault usability concern

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#147]
Too much to ask the user to pre-create Key Vault and populate it with certificate.
* Immediate plan.  Microsoft will: 
  * ~[Ed create tutorial on docs.microsoft.com, sibling to existing AAD tutorial.](https://github.com/edburns/azure-dev-docs/blob/edburns-msft-dd-1165925-wls-aag-key-vault-public/articles/java/migration/migrate-weblogic-with-app-gateway.md)~
  * ~[Update createUiDefinition with link to that doc, and others]()~
    * ~Show Jacob the aka.ms idea~
  * ~Merge changes from galiacheng to develop~
  * ~Verify CI/CD is clean [run 209598386](https://github.com/wls-eng/arm-oraclelinux-wls-cluster/actions/runs/209598386).  Success.  Created issue [AB#1165848](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1165848)~
  * ~Create zip bundle of cluster offer from develop and test in Microsoft test account~ [arm-oraclelinux-wls-cluster-1.0.300000-arm-assembly.zip](https://github.com/wls-eng/arm-oraclelinux-wls-cluster/suites/1053952615/artifacts/14206122)
  * ~Certify zip bundle for deployment to Partner center.  Testing in Offer ID: `20200429-edburns-04`.~
* Immediate plan: Oracle will:
  * ~Update docs~
    * ~Add note before "Table 3-2 Fields in the Azure Application Gateway Blade"  that points to the new doc.~
  * Deploy zip bundle to Partner Center

**Comment by edburns** [comment]
AB#1165828

**Comment by edburns** [comment]
AB#1165886

**Comment by edburns** [comment]
Hello @jacobt123 I certify that [arm-oraclelinux-wls-cluster-1.0.300000-arm-assembly](https://github.com/wls-eng/arm-oraclelinux-wls-cluster/suites/1058798159/artifacts/14341427) is ready to publish as the zip for the Configured Cluster offer in Partner Center.

**Comment by jacobt123** [comment]
Hello @edburns, Version 1.0.300000 published  to Partner Center. Will let you know once the preview is available for testing
