### ISSUE TITLE
Azure Applications: VM size limit is overly restrictive

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#151]
The VM size limit in the ARM template is overly restrictive.  Why?  Can this be relaxed?

**Comment by edburns** [comment]
I will assign this to majguo.

**Comment by majguo** [comment]
## Solution

- remove `allowedValues` for `vmSizeSelect` parameter from templates;
- move `vmSizeSelect` to required sections of `basics`;
- add `excludedSizes` vm sizes and another recommended vm size `Standard_B1ms` to `vmSizeSelect`;

## Relative PRs

- https://github.com/wls-eng/arm-oraclelinux-wls/pull/159
- https://github.com/wls-eng/arm-oraclelinux-wls-admin/pull/45
- https://github.com/wls-eng/arm-oraclelinux-wls-dynamic-cluster/pull/55
- https://github.com/wls-eng/arm-oraclelinux-wls-cluster/pull/73
