### ISSUE TITLE
Configured Cluster: App Gateway UI

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#153]
In `createUiDefinition.json`, 

* modify the regex for `keyVaultResourceGroup` to implement this, from the portal.

> Resource group names only allow alphanumeric characters, periods, underscores, hyphens and parenthesis and cannot end in a period.

> Resource group names only allow up to 90 characters.

* modify the regex for `keyVaultName` to implement this, from the portal.

> Vault name must only contain alphanumeric characters and dashes and cannot start with a number.

> Vault name must be between 3-24 alphanumeric characters. The name must begin with a letter, end with a letter or digit, and not contain consecutive hyphens.

**Comment by edburns** [comment]
I will assign this to @galiacheng .

**Comment by galiacheng** [comment]
Regex for resource group:
```
^[a-z0-9A-Z\\.\\-\\_()]{0,89}([a-z0-9A-Z\\-\\_()]{1})$
```
Test case:
```
# pass
(
()__.__()
haiche_
haiche)
haiche_-
_-
_haiche
.(_._
.........................................................................................1
-_-

# failed
-_-!
..........................................................................................1
haiche;_
haiche.
```

**Comment by galiacheng** [comment]
Regex for vault name
```
^(?=.{3,24}$)[a-zA-Z](([a-z0-9A-Z]*|(?:\-[^\-][a-z0-9A-Z]*))*)$
```
Test cases:
```
# pass
haiche0
haiche-haiche
h-c-c8c-A0-c-cP-c-c-c-c
ha0

# failed
0haiche
haiche-
hc
hh--c
h-----c
h-c-c-c-c-c-c-c-c-c-c-c-c
h-!-c-c-c-c-c-c
```

**Comment by edburns** [comment]
On branch develop
modified:   arm-oraclelinux-wls-cluster/src/main/arm/createUiDefinition.json

Reverted lines that cause this failure in the version of ARM TTK currently in use.

    [-] Textboxes Are Well Formed (160 ms)

Something about this regex causes the test to fail.

"regex": "^[a-z0-9A-Z\\.\\-\\_()]{0,89}([a-z0-9A-Z\\-\\_()]{1})$",

It might be time for us to fix https://github.com/wls-eng/arm-oraclelinux-wls/issues/118 ?
