### ISSUE TITLE
Move `commandToExecute` properties that include passwords to `protectedSettings`

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#158]
For every ARM template in single node, admin, and dynamic cluster offers, make it so every time a `commandToExecute` property appears within a `settings` property, it is moved to a sibling `protectedSettings` property.  Take this diff as an example.

```diff
--- a/deletenode/src/main/arm/mainTemplate.json
+++ b/deletenode/src/main/arm/mainTemplate.json
@@ -120,7 +120,9 @@
                 "settings": {
                     "fileUris": [
                         "[uri(parameters('_artifactsLocation'), concat('scripts/', variables('name_scriptDeleteNode'), parameters('_artifactsLocationSasToken')))]"
-                    ],
+                    ]
+                },
+                "protectedSettings": {
                     "commandToExecute": "[concat('sh',' ', variables('name_scriptDeleteNode'), ' ', parameters('wlsUserName'),' ',parameters('wlsPassword'),' ',array.join(parameters('deletingManagedServerNames')),' ',array.join(parameters('deletingManagedServerMachineNames')),' ', parameters('wlsForceShutDown'), ' ', parameters('adminVMName'), ' ',variables('const_wlsAdminPort'),' ',variables('const_wlsHome'))]"
                 }
             }
```

This work has already been done in the configured cluster offer.

**Comment by majguo** [comment]
## Relative PRs

- https://github.com/wls-eng/arm-oraclelinux-wls-admin/pull/46
- https://github.com/wls-eng/arm-oraclelinux-wls-dynamic-cluster/pull/56

## Note

Single node offer doesn't need according change as no VM extension script will be executed during deployment.

**Comment by majguo** [comment]
Closing the issue as the relative PRs were merged.
