### ISSUE TITLE
Q2 Release Hot Fix remediation

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#162]
Upon the offers going live, it has come to light that the updates to the marketing text of the VM images caused a bump in the version numbers, which invalidated the ARM templates of the Azure Application offers.  This user story tracks the remediation efforts for this problem.

admin: Review and Publish pressed
single node: Saved as draft 1.0.18
cluster: Saved as draft 1.0.330000
dynamic cluster: Saved as draft 1.0.20

**Comment by edburns** [comment]
admin: Review and Publish pressed
single node: Saved as draft 1.0.18
cluster: Saved as draft 1.0.330000
dynamic cluster: Saved as draft 1.0.20

**Comment by galiacheng** [comment]
@edburns  we need to apply the latest version to 2020-07-30-01-Q2.
