### ISSUE TITLE
SSL Configuration for admin node for Dynamic and Configured Cluster Offer

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#170]
Problem: the hostname for the app gateway (and admin console) are auto generated using a guid to ensure uniqueness.  However, SSL certs must have a hard-coded hostname.  We have two choices at deployment time:
1. Allow the user to provide the hostname as a parameter.  We would have to assume the provided hostname is unique.
   ~a. Allow the user to provide the value that is used as the guid.  In the ARM template, if this value is set, use it instead of calling the guid function.~
1. ~Allow the user to derive what the hostname will be.~

**Comment by edburns** [comment]
Jacob and I discussed this today and we agreed to a simplifying assumption: we assume the user will provide a value that, when combined with the rest of the parts of the name, will be a unique hostname.

**Comment by edburns** [comment]
## User Experience

1. Update the App Gateway blade to have a field that accepts the fully qualified DNS name to bind to the public IP for the App Gateway.  We assume this DNS name already exists.  This is based on [Integrate Azure DNS](https://docs.microsoft.com/en-us/azure/dns/dns-custom-domain).  If not specified, the existing guid-based approach is used.
2. Update the ARM template to account for this provided DNS name.

**Comment by gnsuryan** [comment]
I was able to configure an Azure DNS Alias for the WebLogic Admin Server and the Application Gateway in the WebLogic Cluster Offer.

Following are the steps followed to complete the setup:

1. Registered the Domain - wlseng-azuretest.com
2. Created a DNS Zone in the same Resource Group where the WebLogic Admin Server & Application Gateway are already created.
3. Note down the Name Servers associated with the DNS Zone and update them as the name servers in the Registered Domain (This step is called Azure DNS Delegation)
4. Run the command **nslookup -type=SOA wlseng-azuretest.com** to ensure that the configured Azure Name Servers are listed as the name servers for the domain.
5.   Create an Azure DNS alias (subdomain) for the Public IP Address of the WebLogic Admin Server & Application Gateway
     - admin.wlseng-azuretest.com
     - appgw.wlseng-azuretest.com
6. Access the URLs using the wlseng-azuretest.com domain.

      **WebLogic Admin Server**
       http://admin.wlseng-azuretest.com:7001/console/login/LoginForm.jsp
       https://admin.wlseng-azuretest.com:7002/console/login/LoginForm.jsp

     **Application Gateway**
       http://appgw.wlseng-azuretest.com/replicationwebapp/FirstServlet
       https://appgw.wlseng-azuretest.com/replicationwebapp/FirstServlet

**Comment by edburns** [comment]
Thanks @gnsuryan .  Let me spell out the steps I see to automate this process with template deployment.

1. Modify the **createUiDefinition** for the cluster offer.  Modify the App Gateway blade.   Make it so the UI has a text field that allows the user to input a fully qualified domain name, assumed to be pre-created and already in public DNS.
1. Modify the app gateway nested template.
1. If the DNS field was filled in
   1. Create DNS zone using knowledge from [docs](https://docs.microsoft.com/en-us/azure/dns/dns-get-started-template)
   1. Do the necessary delegation actions from [docs](https://docs.microsoft.com/en-us/azure/dns/dns-delegate-domain-azure-dns).
   1. Make it so the public hostname of the App Gateway is the one provided in the text field. This will involve lots of conditionality, particularly in the parts that formerly used the `guid`.
   1. Make it so the template spits out the ip addresses of the nameservers so the user can add them to the pre-created DNS entry.

I may have missed something, but this should be a good starting point for the work.

**Comment by edburns** [comment]
@gnsuryan please determine if the above actions are better implemented as an entirely separate nested template that just deals with the DNS actions, or if, as I was writing, they are better implemented as modifications to the app gateway nested template.  I'm not sure right now.

**Comment by gnsuryan** [comment]
I tried including the ns1-01.azure-dns.com. in the list of default name servers (that starts with @ symbol ). 

I am getting the following error message during deployment.
Deployment failed. Correlation ID: 6dcdadc0-a465-46ad-bf0d-a9fb783b1375. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
          {
            "code": "BadRequest",
            "message": "{\r\n  \"code\": \"BadRequest\",\r\n  \"message\": \"The 'nsdname' of a record set with type 'NS' and name '@' cannot be changed.\"\r\n}"
          }
        ]
      }
    ]

As per the Azure DNS operations documentation, I found that we will not be able to add/delete/modify the name servers which get created by default.

**You cannot add, remove, or modify the records in the automatically created NS record set at the zone apex (--Name "@", including quote marks). For this record set, the only changes permitted are to modify the record set TTL and metadata.**

[https://docs.microsoft.com/en-us/azure/dns/dns-operations-recordsets-cli](https://docs.microsoft.com/en-us/azure/dns/dns-operations-recordsets-cli)

**Comment by gnsuryan** [comment]
The only option left now is to use the default Name Servers created by Azure and output them after deployment is complete, so that users can then use it for Azure DNS Delegation at their Domain Registry.

**Comment by gnsuryan** [comment]
I have completed the creation of Azure DNS Zone and DNS Alias (A) record entry for WebLogic Administration console (in Admin Only, Cluster & Dynamic Cluster offers) and DNS Alias Record (A) entry for Azure Application Gateway for Cluster offer.

Currently, I am working on making changes to the createUIDefinition.json file to accept user inputs for Custom SSL and DNS Configuration.

**Comment by gnsuryan** [comment]
I have completed the changes to createUIDefinition.json file to accept users inputs for Custom SSL and DNS configurations for all the three offers (admin Only, Cluster & Dynamic Cluster).

I am currently working on merging the changes in to the wls-eng branch, as there are many changes that have happened in the last few weeks. I will merge the changes, test and then create a Pull Request once everything is found to be working fine.

**Comment by edburns** [comment]
Notes for 2020-12-23 Weekly Oracle sync

- What is the status of this work and #185 ?
- If the work is stalled, please share the current state, because are working on this regarding #145.
- If the work is still ongoing, we need coordinate integrating it with our work on #145 .

**Comment by edburns** [comment]
Hello @gnsuryan This one is very important for the Q1 release.  We are counting on you to implement this feature for the Dynamic and Configured Clusters, in similar to what you did on the admin offer.  After you have done it, @zhengchang907  will improve the experience similar to what he did on the admin offer.

**Comment by zhengchang907** [comment]
@edburns @gnsuryan I've created related task for adding key vault automation to the SSL configuration blade for the Configured Clusters offer #AB1275906
