### ISSUE TITLE
Load Balancer for Dynamic Cluster Offer

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#177]
Track the progress of making it so OHS as load balancer works for Dynamic Cluster offer.

**Comment by sanjaymantoor** [comment]
Azure ARM template deployment with OHS installation configuration scripts are created.
Able to setup OHS server on Azure VM using ARM deployment. 
Testing OHS setup with dynamic cluster. Working on minor issues noticed during testing.

**Comment by sanjaymantoor** [comment]
Azure ARM OHS template is made as nested template for dynamic cluster.
Dynamic cluster mainTemplate.json invokes ohsNestedTemplate.json once after clusterTemplate.json.
ohsNestedTemplate makes use of some values like "storage account", "virtual network" and "admin url" from clusterTemplate. OHS setup will be made on new VM, which makes use of existing resources "storage account" and "virtual network"
Issue with respect to OHS handling scaling up/down is fixed. Now OHS server able to discover new cluster members and route the request to new managed servers.

**Comment by sanjaymantoor** [comment]
Working on OHS SSL termination. OHS uses Oracle Wallet, which needs to be created at OHS Server VM and give a reference. Changes with respect to Oracle Wallet is completed. Tested with self signed certificates which makes use of JKS certificate.
Working on PKCS12 support changes.

**Comment by sanjaymantoor** [comment]
Able to create OHS base images successfully on Oracle Linux 7.3, 7.4 and 7.6.
Also able to make use of base images for dynamic cluster testing.
Currently testing the OHS with all WebLogic version combinations.

**Comment by edburns** [comment]
@sanjaymantoor  this is great news!

**Comment by edburns** [comment]
@sanjaymantoor can you please give me an estimate on when the PR will be ready for review? I currently see [no open PRs on the dynamic cluster repo](https://github.com/wls-eng/arm-oraclelinux-wls-dynamic-cluster/pulls).

**Comment by sanjaymantoor** [comment]
@edburns 
I have created PR https://github.com/wls-eng/arm-oraclelinux-wls-dynamic-cluster/pull/82 for OHS as load balancer for dynamic cluster.

**Comment by edburns** [comment]
Hello @sanjaymantoor , I have merged https://github.com/wls-eng/arm-oraclelinux-wls-dynamic-cluster/pull/82. I made formatting changes before doing so.
