### ISSUE TITLE
Enhance nsg rule sub template

### ISSUE THREAD

**Issue by galiacheng** [wls-eng/arm-oraclelinux-wls#192]
This is an enhancement for https://github.com/wls-eng/arm-oraclelinux-wls/issues/58.
### Consider requirements:
1. enable the nsg rules during deployment from Azure portal
2. enable the nsg rules after an initial deployment

#### For r1 we can create Azure UI control to set whether to deny access to managed server or not. 

As shown in the following image, add an option `Deny access Managed Servers via Public IP`, `Yes` by default.

![image](https://user-images.githubusercontent.com/59823457/98650964-97822780-2374-11eb-93c4-d498403aa4b3.png)

#### For r2 allow to run the nsg sub template separately.
Suggested path for the sub template:
arm-oraclelinux-wls-cluster/src/main/arm/nestedtemplates/nsgNestedTemplate.json

#### Actions to enhance the nsg sub template

1.  Create an [OptionsGroup ](https://docs.microsoft.com/azure/managed-applications/microsoft-common-optionsgroup?WT.mc_id=Portal-Microsoft_Azure_CreateUIDef)element as a condition to run the template
2.  Move the nsg template to arm-oraclelinux-wls-cluster/src/main/arm/nestedtemplates/nsgNestedTemplate.json
3. Invoke the template in arm-oraclelinux-wls-cluster/src/main/arm/mainTemplate.json with condition
4. Create GitHub page for running nsgNestedTemplate.json independently
5. Add CI/CD step to test the sub template deployment, we have example for db, application gateway in build.yaml.
6. Update microsoft doc https://docs.microsoft.com/en-us/azure/developer/java/migration/migrate-weblogic-with-app-gateway

**Comment by galiacheng** [comment]
@edburns  @sanjaymantoor  @jacobt123 please review the requirement and add your comment.

**Comment by sanjaymantoor** [comment]
My suggestions to this

1.  Deny access option should be available for both admin console port (7001,7002) as well
    There can be 2 options
    - One for admin console port ( 7001, 7002)
    - One for managed server ports (8001 - range)
2. Admin and managed server ports are independent of appgateway , hence I feel it is good to put these options under Basics tab section 
3. There can be two NSG nested templates , one for admin and another one for managed server.
Depending on user choice #1  these NSG templates can be invoked
4. NSG rules should be in such a way that is user wants to gain post deployment either admin/managed ports, then with public ip mention in NSG rule it should be accessible to that ip.

I have already listed those NSG rules at https://github.com/sanjaymantoor/arm-oraclelinux-wls-cluster/blob/develop/addnsgrule/src/main/arm/mainTemplate.json
This template can be split into two one for nsgNestedAdminTemplate.json and nsgNestedManagedTemplate.json.

Appgateway infrastructure ports NSG can be part of default NSG section.

**Comment by edburns** [comment]
@jacobt123 and I reviewed this and request the following modifications.

- The setting should be such that "deny" is selected by default. We may need to account for this change in our testing.  We **will** need to account for this change in our documentation.
- Please do move the setting to the basics blade.
- Please do modify the UI to account for @sanjaymantoor 's suggestion of "one for admin console" and "one for managed servers".
- Please do modify to have two nested templates.
- Please do `git rm` on @sanjaymantoor 's existing `addnsgrule/src/main/arm/mainTemplate.json`.

**Comment by edburns** [comment]
@galiacheng  and I discussed this in our stand-up meeting today and need some guidance about the way forward for this feature.

If we put the feature on the "basics" blade, then it is possible for the user to make their cluster inaccessible if they do not choose to have an App Gateway configured.  

> @sanjaymantoor > Admin and managed server ports are independent of appgateway , hence I feel it is good to put these options under Basics tab section


What is the motivation for putting the feature on the "basics" blade instead of the "App Gateway" blade?  It seems like the feature is tightly coupled with the App Gateway.

Also, if we set the default to be "deny" for both Admin and Worker Nodes in the NSG, then the cluster will be inaccessible as well.

**Comment by sanjaymantoor** [comment]
Initial discussion with our internal stand-up meeting was to block admin and managed server ports. If user wants to gain access then NSG rule can explicitly modified by adding public IP of user machine. By that user can regain access to admin server console and cluster.
I will put your comment in further discussion with our internal meeting. It needs to be decided whether we can always block managed server ports or only during ap gateway instance. If it is only during app gateway instance then choice should be under appgateway tab.

**Comment by edburns** [comment]
@jacobt123  and @edburns  discussed this today and have the following recommendations:

- On the "Basics" blade, have the UI to deny/allow the ports for the admin server.
- On the "App Gateway" blade, have the UI to deny/allow the ports for the worker nodes.

**Comment by zhengchang907** [comment]
PRs:
Dynamic Cluster: https://github.com/wls-eng/arm-oraclelinux-wls-dynamic-cluster/pull/93
Configured Cluster: https://github.com/wls-eng/arm-oraclelinux-wls-cluster/pull/110
Admin: https://github.com/wls-eng/arm-oraclelinux-wls-admin/pull/73
