### ISSUE TITLE
CI/CD failure on verifying Weblogic Server Access

### ISSUE THREAD

**Issue by galiacheng** [wls-eng/arm-oraclelinux-wls#194]
This failure happened since Nov 11th, latest build always failed on image `owls-122130-8u131-ol73;Oracle:weblogic-122130-jdk8u131-ol73:owls-122130-8u131-ol7;latest`.

**Comment by galiacheng** [comment]
Close this issue, the latest builds worked fine. Will reopen if needed.

**Comment by sanjaymantoor** [comment]
I am checking at https://github.com/wls-eng/arm-oraclelinux-wls-cluster/actions
It looks many times it is failing but it is passing in between also. I will look into it.

**Comment by galiacheng** [comment]
Thanks for your checking @sanjaymantoor

**Comment by galiacheng** [comment]
@sanjaymantoor  I found that most of failures were caused by "connection closed by remote server". 
There may be something to do with SSH.
I found few failure on the first SSH connection that verifies WLS installation using `verify-wls-path.sh`.

I have two suggestion to fix the failure:

- For `verify-wls-access.sh` use public IP to access the WLS and execute the script in Ubuntu machine that GitHub allocates.

- For other script that have to been executed using SSH, [restart the remote SSH](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/vmaccess#restart-ssh) before running the `sshpass` command.

**Comment by galiacheng** [comment]
A tip to keep the failure machines:

Change the condition of the following step to `success()`. Pls do not forget to remove the resource after investigation.
```
 - name: Delete Resource Group
      id: delete-resource-group
      if: success()
```

**Comment by sanjaymantoor** [comment]
Yes, even I noticed same. Seeing script is exiting without next command executed.

**Comment by galiacheng** [comment]
Hello @sanjaymantoor FYI given you are busy on the hotfix, I am trying to fix this issue with my previous proposal in my repo.
