### ISSUE TITLE
Create tag 2020-12-02-01-Q4

### ISSUE THREAD

**Issue by galiacheng** [wls-eng/arm-oraclelinux-wls#197]
We need to create tag to include changes of ELK and Coherence.

I have issued PRs to create tag with one click:

- [wls-singlenode-new-tag](https://github.com/wls-eng/arm-oraclelinux-wls/pull/198)
- [wls-admin-new-tag](https://github.com/wls-eng/arm-oraclelinux-wls-admin/pull/64) 
- [wls-cluster-new-tag](https://github.com/wls-eng/arm-oraclelinux-wls-cluster/pull/96)
- [wls-dynamic-cluster-new-tag](https://github.com/wls-eng/arm-oraclelinux-wls-dynamic-cluster/pull/75)

After these PRs are merged, trigger the `New Tag` pipeline and set input value to create a new tag.
![image](https://user-images.githubusercontent.com/59823457/100967859-3a405700-356b-11eb-839f-2d14587fdd37.png)

### Inputs for `2020-12-02-01-Q4`
**Singlenode offer:**
Tag Name: `2020-12-02-01-Q4`
Git Ref: keep default value

**Admin offer:** 
Tag Name: `2020-12-02-01-Q4`
Git Ref: `daf8fc5bf0deb9536626d0d7235362b29e72a5ec`

https://github.com/wls-eng/arm-oraclelinux-wls-admin/commit/99d16dc73d7385b9146a6707398bed2ad6fa2b27 changed the admin console port to `7005`, while the live offer is still using `7001`. So tag `2020-12-02-01-Q4` will not include this commit. It will be included in next tag.

**Cluster offer:**
Tag Name: `2020-12-02-01-Q4`
Git Ref: keep default value

**Dynamic cluster offer:**
Tag Name: `2020-12-02-01-Q4`
Git Ref: keep default value

Please let @galiacheng know if using a new tag name, as she is working on GitHub pages for ELK and Coherence, she will change the tag name correspondingly.

**Comment by galiacheng** [comment]
Need to create GitHub secrets USER_EMAIL and USER_NAME in https://github.com/wls-eng/arm-oraclelinux-wls.

**Comment by jacobt123** [comment]
@galiacheng this is already done. Ed had requested last week and this was done on 12/10

**Comment by galiacheng** [comment]
@jacobt123  cool, thank you, Jacob! Ed will create the tag, just make sure there are secrets to create a branch for pids.

**Comment by galiacheng** [comment]
We have 2020-12-02-01-Q4 tag for 4 offers, close this issue.
