### ISSUE TITLE
Apply Coherence patches to 12.2.1.4.0 images

### ISSUE THREAD

**Issue by galiacheng** [wls-eng/arm-oraclelinux-wls#202]
Error: failed to configure Coherence cluster with image `WebLogic Server 12.2.1.4.0 Base Image and JDK8u251 on OL7.6`.

**Influenced branch**
arm-oraclelinux-wls-cluster/develop
arm-oraclelinux-wls-dynamic-cluster/develop

**Influenced images**
`WebLogic Server 12.2.1.4.0 Base Image and JDK8 on OL7.6`
`WebLogic Server 12.2.1.4.0 Base Image and JDK8u251 on OL7.6`

**Details**
After 2020-11-14 update on base image `WebLogic Server 12.2.1.4.0 Base Image and JDK8u251 on OL7.6`, error happened with the Coherence cluster configured.

Please see the debug info from [CI/CD failure on validating delete node template](https://github.com/wls-eng/arm-oraclelinux-wls/issues/199)

**Requirement**
To fix the issue, we have to apply
patch [30689820](https://support.oracle.com/epmos/faces/PatchSearchResults?_adf.ctrl-state=opw2q9c43_4&_afrLoop=150710385165868)(WebLogic 12.2.1.4.191220)
patch [30729380 ](https://support.oracle.com/epmos/faces/PatchSearchResults?_adf.ctrl-state=opw2q9c43_4&_afrLoop=150944331690675)(Coherence 12.2.1.4.3)

**Test**
After applying the two patched using OPatch, I could start Coherence servers without exception.

**TBD**
Apply the patches to new image `WebLogic Server 12.2.1.4.0 Base Image and JDK8 on OL7.6`
Apply the patches to existing image `WebLogic Server 12.2.1.4.0 Base Image and JDK8u251 on OL7.6` ?

**Reference**
[After Applying Patch 30689820(WLS 12.2.1.4.191220) Managed Server Fails To Start Due To Coherence Errors (Doc ID 2634266.1)](https://support.oracle.com/epmos/faces/DocumentDisplay?_afrLoop=150592462689598&parent=EXTERNAL_SEARCH&sourceId=PROBLEM&id=2634266.1&_afrWindowMode=0&_adf.ctrl-state=opw2q9c43_93)

**Comment by galiacheng** [comment]
Hello @jacobt123 @edburns  could you take a look at this issue? Thanks!

**Comment by edburns** [comment]
Thanks for finding this @galiacheng .

**Comment by edburns** [comment]
Discussed at 2020-12-16 meeting. Resolved to act on this after the 20201202-hotfix release is live.

**Comment by jacobt123** [comment]
@galiacheng Updated image WebLogic Server 12.2.1.4.0 Base Image and JDK8 on OL7.6. Once its in preview, please check if it fixes the failure with Coherence

**Comment by galiacheng** [comment]
@jacobt123 I will have a look today, thank you!

**Comment by galiacheng** [comment]
The image offer is still in Preview creation, will check it again tomorrow.
![image](https://user-images.githubusercontent.com/59823457/106112968-ddd36f80-6188-11eb-9385-2bdd8e3dca4e.png)

**Comment by edburns** [comment]
@galiacheng @jacobt123 confirmed this is testable now. Can you please give it another try?

**Comment by galiacheng** [comment]
@jacobt123 @edburns  I have verified the preview image WebLogic Server 12.2.1.4.0 Base Image and JDK8 on OL7.6, the deployment succeeded . I deployed an coherence application to the cluster, it worked fine.

![image](https://user-images.githubusercontent.com/59823457/107187873-a46cf080-6a21-11eb-8232-a7633f375da1.png)
