### ISSUE TITLE
Update doc for app gateway

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#213]
Update Microsoft Tutorial: https://docs.microsoft.com/en-us/azure/developer/java/migration/migrate-weblogic-with-app-gateway

[AB#1259896](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1259896)

**Comment by galiacheng** [comment]
Close this issue, we have #245 @edburns is working on now.
