### ISSUE TITLE
Update Oracle Docs to account for deployment time hide/show of admin and managed server ports

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#219]
Places in the Oracle docs that need updates for this feature.

- https://docs.oracle.com/en/middleware/standalone/weblogic-server/wlazu/deploy-oracle-weblogic-server-administration-server-single-node1.html
- https://docs.oracle.com/en/middleware/standalone/weblogic-server/wlazu/deploy-oracle-weblogic-server-n-node-configured-cluster.html
- https://docs.oracle.com/en/middleware/standalone/weblogic-server/wlazu/deploy-oracle-weblogic-server-n-node-dynamic-cluster.html

@zhengchang907  will provide exact proposed text along the lines of "after the bullet point 'Ports and port ranges to expose (N or N-N, comma separated): Specify the ports that you want to allow in the Azure network group pr..." add this text <Zheng's text here>".

**Comment by edburns** [comment]
AB#1267991

**Comment by zhengchang907** [comment]
For single node/configured cluster/dynamic cluster offers, in the Basic blade section, after bullet point 'Ports and port ranges to expose (N or N-N, comma separated)...', please add another bullet point as follows:
--------------- text start ---------------
**Deny public traffic for admin server?**: Choose the option of how you'd like to manage the public traffic of the admin server. When you select 'yes', additional Inbound Security Rules will be added to the Azure Network Security Group during deployment. The appended rules will deny public traffic for port 7001 and 7002. Please note that this configuration has a higher priority than configuration at 'Ports and port ranges to expose'.
-------------- text end --------------- 

For configured cluster/dynamic cluster offers, in the Application Gateway blade section, before the field 'Resource group name in current subscription containing the KeyVault', please add another field as follows:

-------------- text start --------------- 
|field|description|
|---|---|
|Deny public traffic for managed server?|Choose the option of how you'd like to manage the public traffic of the managed server. When you select 'yes', additional Inbound Security Rules will be added to the Azure Network Security Group during deployment. The appended rules will deny public traffic for port 8001. Please note that this configuration has a higher priority than the configuration at 'Ports and port ranges to expose' in Basic blade.|

-------------- text end --------------- 

-------------------------------------------------------------------------------------------------------------------
**PS: For the dynamic cluster offer, currently we don't have the Appcliation Gateway blade section yet.**
