### ISSUE TITLE
Instructions for documenting how to use OHS as load balancer for Dynamic Cluster offer

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#221]
- Portal Documentation
- GitHub Pages Documentation

**Comment by sanjaymantoor** [comment]
[Oracle HTTP Server Usage for Dynamic Cluster.pdf](https://github.com/wls-eng/arm-oraclelinux-wls/files/6109315/Oracle.HTTP.Server.Usage.for.Dynamic.Cluster.pdf)

**Comment by sanjaymantoor** [comment]
I have attached Oracle HTTP Server usage for dynamic cluster documentation.
