### ISSUE TITLE
Update OHS UI definitions and setupOHS script for dynamic cluster

### ISSUE THREAD

**Issue by sanjaymantoor** [wls-eng/arm-oraclelinux-wls#222]
- Update enableOHS output parameter
- Add default values for HTTP/HTTPS port
- Handling start/stop component with supplied OHS_COMPONENT_NAME parameter
- Display ohs access url for user information at execution output

**Comment by galiacheng** [comment]
Hello @sanjaymantoor can we set default value to domain name and component name also?

**Comment by sanjaymantoor** [comment]
Sure, I will include default values to domain and component names as well.
