### ISSUE TITLE
Instructions for documenting SSL Configuration on Configured and Dynamic Cluster Blades

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#237]
See [AB#1273384](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1273384).

**Comment by gnsuryan** [comment]
The SSL Configuration blade has already been documented as follows for both Configured and Dynamic Cluster Offers:

<div class="section">
                  <p class="subhead1"><b>SSL Configuration</b></p>
                  <p>The <b>SSL Configuration</b> allows you to configure Oracle WebLogic Administration Console on a secure HTTPS port, with your own SSL certificate provided by a Certifying Authority.
                  </p>
                  <p>Set the toggle button <b>Configure WebLogic Administration Console on HTTPS (Secure) Port, with your own SSL Certificate provided by a Certifying Authority?</b> to <b>Yes</b> or <b>No</b> based on your preference. If you set it to <b>No</b>, you do not have to enter any details, and can proceed by clicking <b>Next &gt;</b>. If you set it to <b>Yes</b>, you must choose either to upload existing KeyStores or use the KeyStores stored in Azure Key Vault.
                  </p>
                  <p>If you want to upload existing KeyStores, select <b>Upload existing KeyStores</b> for <b>How would you like to provide required configuration</b>, and enter the values for the fields in the following table:
                  </p>
                  <div class="tblformal">
                     <p class="titleintable">Table - <b>Fields in the SSL Configuration Blade for Uploading Existing KeyStores</b></p>
                     <table cellpadding="4" cellspacing="0" class="Formal" title="Fields in the SSL Configuration Blade for Uploading Existing KeyStores" summary="This table lists the fields in the SSL Configuration blade for uploading existing KeyStores,when deploying Oracle WebLogic Server configured cluster." frame="hsides" border="1" rules="rows">
                        <thead>
                           <tr align="left" valign="top">
                              <th align="left" valign="bottom">Field</th>
                              <th align="left" valign="bottom">Description</th>
                           </tr>
                        </thead>
                        <tbody>
                           <tr align="left" valign="top">
                              <td align="left" valign="top"><b>Custom Identity KeyStore Data file(.jks,.p12)</b></td>
                              <td align="left" valign="top">Upload a custom identity keystore data file by clicking the file icon, selecting the file, and then clicking <span class="uicontrol bold">Open</span>.
                              </td>
                           </tr>
                           <tr align="left" valign="top">
                              <td align="left" valign="top"><b>Password</b></td>
                              <td align="left" valign="top">Enter a passphrase for the custom identity keystore.</td>
                           </tr>
                           <tr align="left" valign="top">
                              <td align="left" valign="top"><b>Confirm password</b></td>
                              <td align="left" valign="top">Re-enter the passphrase for the custom identity keystore.</td>
                           </tr>
                           <tr align="left" valign="top">
                              <td align="left" valign="top"><b>The Custom Identity KeyStore type (JKS,PKCS12)</b></td>
                              <td align="left" valign="top">Select the type of the custom identity keystore. The supported values are JKS and PKCS12.</td>
                           </tr>
                           <tr align="left" valign="top">
                              <td align="left" valign="top"><b>Custom Trust KeyStore Data file(.jks,.p12)</b></td>
                              <td align="left" valign="top">Upload a custom trust keystore data file by clicking the file icon, selecting the file, and then clicking <span class="uicontrol bold">Open</span>.
                              </td>
                           </tr>
                           <tr align="left" valign="top">
                              <td align="left" valign="top"><b>Password</b></td>
                              <td align="left" valign="top" headers="d6214e469 d6214e429 ">Enter a passphrase for the custom trust keystore.</td>
                           </tr>
                           <tr align="left" valign="top">
                              <td align="left" valign="top"><b>Confirm password</b></td>
                              <td align="left" valign="top">Re-enter the passphrase for the custom trust keystore.</td>
                           </tr>
                           <tr align="left" valign="top">
                              <td align="left" valign="top" ><b>The Custom Trust KeyStore type (JKS,PKCS12)</b></td>
                              <td align="left" valign="top" >Select the type of the custom trust keystore. The supported values are JKS and PKCS12.</td>
                           </tr>
                           <tr align="left" valign="top">
                              <td align="left" valign="top"><b>The private Key Alias</b></td>
                              <td align="left" valign="top" >Specify the alias for the private key.</td>
                           </tr>
                           <tr align="left" valign="top">
                              <td align="left" valign="top"><b>The passphrase for the Private Key</b></td>
                              <td align="left" valign="top">Enter a passphrase for the private key.</td>
                           </tr>
                           <tr align="left" valign="top">
                              <td align="left" valign="top"><b>Confirm passphrase</b></td>
                              <td align="left" valign="top">Re-enter the passphrase for the private key.</td>
                           </tr>
                        </tbody>
                     </table>
                  </div>
                  
                  <p>If you want to use the KeyStores stored in Azure Key Vault, select <b>Use KeyStores stored in Azure Key Vault</b> for <b>How would you like to provide required configuration</b>, and enter the values for the fields in the following table:
                  </p>
                  <div class="tblformal">
                     <p class="titleintable">Table - <b> Fields in the SSL Configuration Blade for Using KeyStores Stored in the Azure Key Vault</b></p>
                     <table cellpadding="4" cellspacing="0" class="Formal" title="Fields in the SSL Configuration Blade for Using KeyStores Stored in the Azure Key Vault" summary="This table lists the fields in the SSL Configuration blade for using KeyStores stored in Azure Key Vault, in case of deploying Oracle WebLogic Server configured cluster." frame="hsides" border="1" rules="rows">
                        <thead>
                           <tr align="left" valign="top">
                              <th align="left" valign="bottom">Field</th>
                              <th align="left" valign="bottom">Description</th>
                           </tr>
                        </thead>
                        <tbody>
                           <tr align="left" valign="top">
                              <td align="left" valign="top" ><b>Resource group name in current subscription containing the KeyVault</b></td>
                              <td align="left" valign="top" >Specify the name of the Resource Group containing the Key Vault that stores the SSL certificate.
                                 <p>An Azure Key Vault is a platform-managed secret store that can be used to safeguard secrets, keys, and TLS/SSL certificates. See <a href="https://docs.microsoft.com/en-us/azure/key-vault/general/overview" target="_blank">About Azure Key Vault</a>.
                                 </p>
                              </td>
                           </tr>
                           <tr align="left" valign="top">
                              <td align="left" valign="top"><b>Name of the Azure KeyVault containing secrets for the SSL Certificate</b></td>
                              <td align="left" valign="top">Specify the name of the Azure Key Vault that stores the secrets for the SSL certificate.</td>
                           </tr>
                           <tr align="left" valign="top">
                              <td align="left" valign="top"><b>The name of the secret in the specified KeyVault whose value is the Identity KeyStore Data</b></td>
                              <td align="left" valign="top">Specify the name of the Azure Key Vault secret that holds the value of the identity keystore data.</td>
                           </tr>
                           <tr align="left" valign="top">
                              <td align="left" valign="top"><b>The name of the secret in the specified KeyVault whose value is the passphrase for the Identity KeyStore</b></td>
                              <td align="left" valign="top">Specify the name of the Azure Key Vault secret that holds the value of the identity keystore passphrase.</td>
                           </tr>
                           <tr align="left" valign="top">
                              <td align="left" valign="top"><b>The Identity KeyStore type (JKS,PKCS12)</b></td>
                              <td align="left" valign="top" >Select the type of the identity keystore. The supported values are JKS and PKCS12.</td>
                           </tr>
                           <tr align="left" valign="top">
                              <td align="left" valign="top"><b>The name of the secret in the specified KeyVault whose value is the Trust KeyStore Data</b></td>
                              <td align="left" valign="top">Specify the name of the Azure Key Vault secret that holds the value of the trust keystore data.</td>
                           </tr>
                           <tr align="left" valign="top">
                              <td align="left" valign="top" ><b>The name of the secret in the specified KeyVault whose value is the passphrase for the Trust KeyStore</b></td>
                              <td align="left" valign="top">Specify the name of the Azure Key Vault secret that holds the value of the trust keystore passphrase.</td>
                           </tr>
                           <tr align="left" valign="top">
                              <td align="left" valign="top"><b>The Trust KeyStore type (JKS,PKCS12)</b></td>
                              <td align="left" valign="top">Select the type of the trust keystore. The supported values are JKS and PKCS12.</td>
                           </tr>
                           <tr align="left" valign="top">
                              <td align="left" valign="top"><b>The name of the secret in the specified KeyVault whose value is the Private Key Alias</b></td>
                              <td align="left" valign="top">Specify the name of the Azure Key Vault secret that holds the value of the private key alias.</td>
                           </tr>
                           <tr align="left" valign="top">
                              <td align="left" valign="top"><b>The name of the secret in the specified KeyVault whose value is the passphrase for the Private Key</b></td>
                              <td align="left" valign="top" headers="d6214e591 d6214e527 ">Specify the name of the Azure Key Vault secret that holds the value of the private key passphrase.</td>
                           </tr>
                        </tbody>
                     </table>
                  </div>
