### ISSUE TITLE
Dynamic cluster createUiDefinition.json throwing error during testing at sandbox

### ISSUE THREAD

**Issue by sanjaymantoor** [wls-eng/arm-oraclelinux-wls#239]
**Issue noticed:**
arm-oraclelinux-wls-dynamic-cluster createUiDefinition.json is throwing following error when it is tested at Azure SandboxBlade.

_"The element for [basics('basicsOptional').useSystemAssignedManagedIdentity] could not be found in the createuidefinition"_

I think recent change "[Add system assigned managed identity and ELK index cleanup (#91)](https://github.com/wls-eng/arm-oraclelinux-wls-dynamic-cluster/pull/91)" has caused the issue.

Probably following is causing the error.

"useSystemAssignedManagedIdentity" section is not under "basicsOptional" but it is referred as `"useSystemAssignedManagedIdentity": "[basics('basicsOptional').useSystemAssignedManagedIdentity]"`
![Dynamic Cluster UI Definition issue](https://user-images.githubusercontent.com/36834780/107060597-2c25e580-67fd-11eb-8c14-a1f1e52199d4.png)
 at outputs section.

Currently live OHS base images skuUrnVersion update and testing is waiting for this fix.

**Comment by sanjaymantoor** [comment]
Currently live OHS base images skuUrnVersion update and testing is waiting for this fix.

**Comment by galiacheng** [comment]
Hello @zhengchang907 , could you have a check, thank you!

**Comment by zhengchang907** [comment]
Thank you @galiacheng!
Hi @sanjaymantoor , thanks for creating the issue. I've located the problem and fired a PR for it: https://github.com/wls-eng/arm-oraclelinux-wls-dynamic-cluster/pull/94

**Comment by zhengchang907** [comment]
@sanjaymantoor Hi Sanjay, the PR is merged, can you please verify & close this issue?

**Comment by sanjaymantoor** [comment]
Changes are merged and tested.
