### ISSUE TITLE
Instructions for documenting Key Vault Automation for OHS

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#249]

**Comment by edburns** [comment]
Please see #245 for link to ms doc containing appropriate text for documenting the options for providing the SSL certificate.

**Comment by sanjaymantoor** [comment]
[Oracle HTTP Server Load Balancer.pdf](https://github.com/wls-eng/arm-oraclelinux-wls/files/6114345/Oracle.HTTP.Server.Load.Balancer.pdf)

**Comment by edburns** [comment]
Discussed at 2021-03-10 meeting, will apply this to be a sibling document for App Gateway on docs.microsoft.com
