### ISSUE TITLE
Incorrect reference to Cluster SSL/normal Template during deployment of dnszonesLinkedTemplate in Dynamic Cluster offer

### ISSUE THREAD

**Issue by gnsuryan** [wls-eng/arm-oraclelinux-wls#252]
Incorrect reference to Cluster SSL/normal Template during deployment of dnszonesLinkedTemplate in Dynamic Cluster offer

Please refer to https://raw.githubusercontent.com/wls-eng/arm-oraclelinux-wls-dynamic-cluster/develop/arm-oraclelinux-wls-dynamic-cluster/src/main/arm/mainTemplate.json

The following line of code is currently:
"targetResources": {
                        "value": "[if(parameters('enableOHS'), createArray(reference('clusterLinkedTemplate', '${azure.apiVersion}').outputs._adminPublicIPId.value, reference('ohsLinkedTemplate', '${azure.apiVersion}').outputs._ohsPublicIP.value), createArray(reference('clusterLinkedTemplate', '${azure.apiVersion}').outputs._adminPublicIPId.value))]"
                    }

It should have been written as:
"targetResources": {
                        "value": "[if(parameters('enableOHS'), createArray(reference(variables'clusterTemplateRef', '${azure.apiVersion}').outputs._adminPublicIPId.value, reference('ohsLinkedTemplate', '${azure.apiVersion}').outputs._ohsPublicIP.value), createArray(reference(variables'clusterTemplateRef', '${azure.apiVersion}').outputs._adminPublicIPId.value))]"
                    }
                    
so, that it works for both SSL/Non-SSL scenarios.

**Comment by galiacheng** [comment]
@gnsuryan Thank you! I will fix it right now. We should include both IP output from SSL and non-SSL.

**Comment by galiacheng** [comment]
Checked:  the IP reference in configured cluster is ok.
