### ISSUE TITLE
'Learn more' on 'Elasticsearch and Kibana' blade leads to a bad page

### ISSUE THREAD

**Issue by zhengchang907** [wls-eng/arm-oraclelinux-wls#265]
@edburns Hi Ed, can you please take a look at this invalid link issue?
![image](https://user-images.githubusercontent.com/74032668/108975441-76460c80-76c1-11eb-9791-bacb3855fefb.png)
In Configured Cluster offer (deployed using latest code on develop branch), the FIRST 'Learn more' page link: https://docs.microsoft.com/en-us/azure/developer/java/migration/migrate-weblogic-with-elk is not valid anymore.

**Comment by edburns** [comment]
@zhengchang907 this PR is not published yet.  See https://github.com/wls-eng/arm-oraclelinux-wls/issues/210#issuecomment-777709296
