### ISSUE TITLE
KeyVaultAppGatewayTemplate fails to deploy if the resource group name is very long.

### ISSUE THREAD

**Issue by gnsuryan** [wls-eng/arm-oraclelinux-wls#276]
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"InvalidDomainNameLabel","message":"The domain name label wlsgw7e4f67-guru-cluster-ssl-keyvault-aad-coh-1411jdk11ol76-wlsd is invalid. It must conform to the following regular expression: ^[a-z][a-z0-9-]{1,61}[a-z0-9]$."}]}

The resource group name used was guru-cluster-ssl-keyvault-aad-coh-1411jdk11ol76. The resource group name is used for setting the domain name label for the Application gateway which has a constraint of max length of 61 characters. Since, the resource group name is very large, the domain label setting fails and therefore the keyvaultAppGateway deployment also fails.
We may have to restrict the number of characters in the resource group name.

**Comment by galiacheng** [comment]
The domain name is invalid. It can contain only lowercase letters, numbers and hyphens. The first character must be a letter. The last character must be a letter or number. The value must be between 3 and 63 characters long.
The domain name label must conform to the following regular expression: ^[a-z][a-z0-9-]{1,61}[a-z0-9]$.
