### ISSUE TITLE
AAD template validation fails with WLS SSL certificate uploading

### ISSUE THREAD

**Issue by sanjaymantoor** [wls-eng/arm-oraclelinux-wls#277]
This issue is noticed only when WLS SSL is configured with SSL certificate uploading option. Issue is happening for all 3 offers wls admin, cluster and dynamic cluster.

Issue noticed:
The resource identifier of the KeyVault parameter 'keyVaultCustomTrustKeyStorePassPhrase' is invalid. Please specify the value following '/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.KeyVault/vaults/{vaultName}' format. See https://aka.ms/arm-keyvault for usage details. (Code: KeyVaultParameterReferenceInvalidResourceId)

{
  "code": "KeyVaultParameterReferenceInvalidResourceId",
  "message": "The resource identifier of the KeyVault parameter 'keyVaultCustomTrustKeyStorePassPhrase' is invalid. Please specify the value following '/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.KeyVault/vaults/{vaultName}' format. See https://aka.ms/arm-keyvault for usage details."
}

**Comment by sanjaymantoor** [comment]
![Issue Noticed](https://user-images.githubusercontent.com/36834780/109458261-760f8d80-7a82-11eb-90a3-895a6ba809bf.png)

**Comment by sanjaymantoor** [comment]
[AAD issue.zip](https://github.com/wls-eng/arm-oraclelinux-wls/files/6059503/AAD.issue.zip)

All the input parameters and issue screen shots are available with this AAD.issue.zip file.

**Comment by zhengchang907** [comment]
```
"keyVaultCustomTrustKeyStorePassPhrase": {
                        "reference": {
                            "keyVault": {
                                "id": "[resourceId(variables('const_currentSubscription'),  parameters('adminSSLKeyVaultResourceGroup'), 'Microsoft.KeyVault/vaults', parameters('adminSSLKeyVaultName'))]"
                            },
                            "secretName": "[parameters('keyVaultCustomTrustKeyStorePassPhraseSecretName')]"
                        }
                    },
                    "keyVaultCustomTrustKeyStoreType": {
                        "value": "[parameters('keyVaultCustomTrustKeyStoreType')]"
                    }
```
In AAD with customSSL enabled, related Secrets need to be referenced

**Comment by zhengchang907** [comment]
PRs:

Configured Cluster: https://github.com/wls-eng/arm-oraclelinux-wls-cluster/pull/127

**Comment by zhengchang907** [comment]
@sanjaymantoor Hi Sanjay, I've fixed the templates and the PRs are merged, can you check on that to double confirm?

Will close the issue now.
