### ISSUE TITLE
AAD certificate input parameter label/help needs to be updated

### ISSUE THREAD

**Issue by sanjaymantoor** [wls-eng/arm-oraclelinux-wls#278]
AAD Configuration section for all 3 offers.

Current AAD server certificate uploading label and help is like below.
Label name :"Trust Keystore for TLS/SSL Configuration ".
Help info :"Custom Trust Keystore of WebLogic Server, used to enable TLS/SSL"

Above information doesn't look relevant if "TLS/SSL Configuration is not selected". As per my understanding this is related to AAD Server certificate .cer file uploading. Hence label and help needs to be updated accordingly.

**Comment by sanjaymantoor** [comment]
<img width="666" alt="AAD certificate uploading label" src="https://user-images.githubusercontent.com/36834780/109459106-23cf6c00-7a84-11eb-92f7-29c355b17f97.png">

**Comment by galiacheng** [comment]
Hello @sanjaymantoor  please have a look at the change, the PRs have been merged. Thank you.
