### ISSUE TITLE
Webapp Deployment fails intermittently with dynamic cluster offer

### ISSUE THREAD

**Issue by zhengchang907** [wls-eng/arm-oraclelinux-wls#280]
-- When deploying webapp on WebLogic Console, I got the following error:
An error occurred during activation of changes, please see the log for details.
[Management:141191]The prepare phase of the configuration update failed with an exception.
Cannot update 'Machine' while the server is running

-- ARM Deployment
---- Only Enable OHS using uploaded KeyStore file with following params:
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "adminPasswordOrKey": {
            "value": null
        },
        "adminRestMgmtURL": {
            "value": "http://adminVM:7001/management/weblogic/latest"
        },
        "adminUsername": {
            "value": "weblogic"
        },
        "authenticationType": {
            "value": "password"
        },
        "dnsLabelPrefix": {
            "value": "wls"
        },
        "guidValue": {
            "value": "a6348c61-d680-4baf-85b9-bc9fc78104c4"
        },
        "keyType": {
            "value": "JKS"
        },
        "location": {
            "value": "eastus"
        },
        "ohsComponentName": {
            "value": "ohs_component"
        },
        "ohsDomainName": {
            "value": "ohsStandaloneDomain"
        },
        "ohsNMPassword": {
            "value": null
        },
        "ohsNMUser": {
            "value": "ohsNMUser"
        },
        "ohsSSLKeystoreData": {},
        "ohsSSLKeystorePassword": {},
        "ohsSkuUrnVersion": {
            "value": "ohs-122140-jdk8-ol76;ohs-122140-jdk8-ol76;latest"
        },
        "ohsVMName": {
            "value": "ohsVM"
        },
        "ohshttpPort": {
            "value": "7777"
        },
        "ohshttpsPort": {
            "value": "4444"
        },
        "oracleVaultPswd": {
            "value": "Secret123456"
        },
        "storageAccountName": {
            "value": "53c22aolvm"
        },
        "virtualNetworkName": {
            "value": "wlsd_VNET"
        },
        "vmSizeSelect": {
            "value": "Standard_A1"
        },
        "wlsPassword": {
            "value": "Secret123456"
        },
        "wlsUserName": {
            "value": "weblogic"
        }
    }
}

**Comment by zhengchang907** [comment]
ohs-122140-jdk8-ol76;ohs-122140-jdk8-ol76;latest this image failed too

**Comment by zhengchang907** [comment]
Tried with "owls-141100-jdk11-ol76;Oracle:weblogic-141100-jdk11-ol76:owls-141100-jdk11-ol7;latest" and it works fine

**Comment by zhengchang907** [comment]
Sometime the ARM deployment failed with following error msg:


{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "VMExtensionProvisioningError",
      "message": "VM has reported a failure when processing extension 'newuserscript'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=1\n[stdout]\ncreating OHS domain configuration file ...\nSetting up OHS standalone domain at /u01/domains/ohsStandaloneDomain\n\nInitializing WebLogic Scripting Tool (WLST) ...\n\nJython scans all the jar files it can find at first startup. Depending on the system, this process may take a few minutes to complete, and WLST may not return a prompt right away.\n\nWelcome to WebLogic Server Administration Scripting Shell\n\nType help() for help on available commands\n\n \n\n\nExiting WebLogic Scripting Tool.\n\nOHS standalone domain is configured successfully\nSetting CrashRecoveryEnabled true at /u01/domains/ohsStandaloneDomain/nodemanager/nodemanager.properties\nCreating NodeManager service\nCreating ohs component service\n-v --user weblogic:Secret123456 -H X-Requested-By:MyClient -H Accept:application/json -H Content-Type:application/json\ncurl http://10.0.0.6:8002/weblogic/ready\n10.0.0.6:8002 is reachable\ncurl http://10.0.0.4:8004/weblogic/ready\n10.0.0.4:8004 is reachable\ncurl http://10.0.0.5:8003/weblogic/ready\n10.0.0.5:8003 is reachable\nCreating backup file for existing mod_wl_ohs.conf file\nCreating mod_wl_ohs.conf file as per 10.0.0.6:8002,10.0.0.4:8004,10.0.0.5:8003\nOracle PKI Tool : Version 12.2.1.4.0\nCopyright (c) 2004, 2019, Oracle and/or its affiliates. All rights reserved.\n\nOperation is successfully completed.\nSuccessfully oracle vault is created\ntotal 8\n-rw-------. 1 oracle oracle 194 Mar  1 10:08 cwallet.sso\n-rw-------. 1 oracle oracle   0 Mar  1 10:08 cwallet.sso.lck\n-rw-------. 1 oracle oracle 149 Mar  1 10:08 ewallet.p12\n-rw-------. 1 oracle oracle   0 Mar  1 10:08 ewallet.p12.lck\nOracle PKI Tool : Version 12.2.1.4.0\nCopyright (c) 2004, 2019, Oracle and/or its affiliates. All rights reserved.\n\nLength is too big: takes 109 bytes\n\n[stderr]\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to adminVM port 7001 (#0)\n*   Trying 10.0.0.7...\n* Connected to adminVM (10.0.0.7) port 7001 (#0)\n* Server auth using Basic with user 'weblogic'\n> GET /management/weblogic/latest/domainRuntime/serverRuntimes?fields=defaultURL HTTP/1.1\r\n> Authorization: Basic d2VibG9naWM6U2VjcmV0MTIzNDU2\r\n> User-Agent: curl/7.29.0\r\n> Host: adminVM:7001\r\n> X-Requested-By:MyClient\r\n> Accept:application/json\r\n> Content-Type:application/json\r\n> \r\n\r  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0< HTTP/1.1 200 OK\r\n< Date: Mon, 01 Mar 2021 10:08:42 GMT\r\n< Content-Length: 2472\r\n< Content-Type: application/json\r\n< X-ORACLE-DMS-ECID: 12f08a54-8280-42de-8566-6510b29353d8-00000060\r\n< X-ORACLE-DMS-RID: 0\r\n< Set-Cookie: JSESSIONID=SSjtQu5Ifs_1pMuSTRFtqYlQJVA8eZxnRFskv7fJZL3aNYRxESRE!1815578965; path=/; HttpOnly\r\n< Vary: Accept-Encoding\r\n< \r\n{ [data not shown]\n\r100  2472  100  2472    0     0    582      0  0:00:04  0:00:04 --:--:--   583\n* Connection #0 to host adminVM left intact\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\nUnable to add PKCS12 certificate to Oracle Wallet\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "
    }
  ]
}

**Comment by sanjaymantoor** [comment]
Issue #1 )
An error occurred during activation of changes, please see the log for details.
[Management:141191]The prepare phase of the configuration update failed with an exception.
Cannot update 'Machine' while the server is running

This issue is intermittent and noticed without OHS also. It looks issue more of WLS Dynamic cluster and we have some internal tracking for this.

Issue #2) ARM deployment failed with following error msg
I am seeing error at
"Unable to add PKCS12 certificate to Oracle Wallet".

This error is directly coming from "orapki" Oracle Wallet utility failure. In my opinion this can happen only if following happens.
a) If certificate supplied format and selected key type is different
b) If  certificate password supplied is wrong  
c) If certificate format is not proper

Please let me know whether still issue is reproducible.

**Comment by sanjaymantoor** [comment]
Refer https://github.com/wls-eng/arm-oraclelinux-wls/blob/gh-pages/dynamic-cluster/ohsNestedTemplate.md

**Comment by zhengchang907** [comment]
I cannot repro Error 2, I might made some mistakes by passing wrong parameters when testing it at the first time.
