### ISSUE TITLE
Dynamic offer: Need more explanation about ‘Oracle Vault Password' on OHS blade

### ISSUE THREAD

**Issue by zhengchang907** [wls-eng/arm-oraclelinux-wls#286]
Hi Guru,

Can you make an update to add more explanation about the Oracle Vault Password? The current hangover text only shows 'Oracle Vault password', we'd like to provide more info to help user understand the parameter.
![image](https://user-images.githubusercontent.com/74032668/109783232-ba4a8b80-7c44-11eb-9970-e492262adddb.png)

CC @edburns

**Comment by gnsuryan** [comment]
Hi Galia @galiacheng , Sanjay had worked on the OHS implementation. I have assigned the bug to him. 
Sanjay will provide the required information for Oracle Vault during OHS configuration.
