### ISSUE TITLE
Need proper help info about Type of certificate at TLS/SSL and OHS blade section in admin,cluster and dynamic offers

### ISSUE THREAD

**Issue by sanjaymantoor** [wls-eng/arm-oraclelinux-wls#300]
Proper help information is required for "Type of the certificate format ( JKS.PKCS12)" for OHS blade for the option "Upload existing KeyStores"

**Comment by sanjaymantoor** [comment]
![OHS Blade](https://user-images.githubusercontent.com/36834780/111644113-874bee80-8825-11eb-865f-be418166ea76.png)

**Comment by sanjaymantoor** [comment]
Instead of "Use only letters and numbers", it should be "Type of the certificate format"

**Comment by sanjaymantoor** [comment]
![TLS-SSL Configuration](https://user-images.githubusercontent.com/36834780/111653696-1b21b880-882e-11eb-84e7-77c39871cf77.png)

**Comment by sanjaymantoor** [comment]
I am seeing proper help info is required on all admin, cluster and dynamic cluster offers for TLS/SSL Configuration as well.

**Comment by edburns** [comment]
PRs
https://github.com/wls-eng/arm-oraclelinux-wls-admin/pull/101
https://github.com/wls-eng/arm-oraclelinux-wls-dynamic-cluster/pull/132
https://github.com/wls-eng/arm-oraclelinux-wls-cluster/pull/144
