### ISSUE TITLE
DNS configuration blade: User assigned managed identity section should be mandatory field 

### ISSUE THREAD

**Issue by sanjaymantoor** [wls-eng/arm-oraclelinux-wls#301]
![User assigned managed identity](https://user-images.githubusercontent.com/36834780/111644803-2c66c700-8826-11eb-854f-055767d1947d.png)

**Comment by edburns** [comment]
> If User assigned managed identity is not selected, deployment validation fails for DNS configuration.

Long story short, this is the correct behavior.

For more details, I observe that the UI control in question [does not support the required property](https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/microsoft-managedidentity-identityselector).
