### ISSUE TITLE
Remove weblogic-deploy-tool downloading as part of setup script

### ISSUE THREAD

**Issue by Lighter100** [wls-eng/arm-oraclelinux-wls#310]
![error_message1](https://user-images.githubusercontent.com/82558518/114809670-30621680-9ddd-11eb-8c8b-e1ae95f370b3.png)
![error_message2](https://user-images.githubusercontent.com/82558518/114809697-4079f600-9ddd-11eb-8265-cdde5de4c4b3.png)

**Comment by galiacheng** [comment]
More information from @Lighter100 

- This is an intermittent issue
- Root cause: failed to download weblogic-deploy-tool.

![image](https://user-images.githubusercontent.com/59823457/114810040-df9eed80-9ddd-11eb-9034-7f19b8b1b7c0.png)

**Comment by sanjaymantoor** [comment]
I will look into it. Sometime back I have noted this intermittent  issue and identified the changes. 
As we are using WebLogic base image, we no need to download JDK or weblogic-deploy-tool.

**Comment by edburns** [comment]
```bash
#Function to create Admin Only Domain
function create_adminSetup()
{
    echo "Creating Admin Setup"
    echo "Creating domain path $DOMAIN_PATH"
    echo "Downloading weblogic-deploy-tool"

    sudo mkdir -p $DOMAIN_PATH
    sudo rm -rf $DOMAIN_PATH/*

    cd $DOMAIN_PATH
    wget -q $WEBLOGIC_DEPLOY_TOOL
    if [[ $? != 0 ]]; then
       echo "Error : Downloading weblogic-deploy-tool failed"
       exit 1
    fi
    sudo unzip -o weblogic-deploy.zip -d $DOMAIN_PATH
```

Looks like this is still downloading the deployment tool.

**Comment by sanjaymantoor** [comment]
Yes, I have done changes and will create PR for the same.
