### ISSUE TITLE
Cluster Offers: Worker Nodes: make public/private IP configurable

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#58]
Currently the offers that create WLS clusters give each worker node a public IP.  Now that we have the ability to have an App Gateway provisioned in front of the cluster, this is no longer necessary or desirable.  This issue requests that work be done to evaluate the right choice with regard to the public/private IP nature of the worker nodes.  Considerations include:

- Should the choice of public or private be configurable?
- Perhaps the choice will be implied based on whether or not an app gateway is provisioned or not?

**Comment by jacobt123** [comment]
Another approach is to modify the existing NSG and deny access by default. Domain administrators can  run a script or via portal provide on demand access to specific IP addresses.

**Comment by edburns** [comment]
AB#1253113

**Comment by sanjaymantoor** [comment]
@jacobt123 @edburns  I believe the pending work for this issue is already covered in issue [Enhance nsg rule sub template #192](https://github.com/wls-eng/arm-oraclelinux-wls/issues/192) . 
@galiacheng Please confirm.

**Comment by galiacheng** [comment]
@jacobt123  @edburns  confirmed with @zhengchang907 we have finished #192 , I will close this issue.
