### ISSUE TITLE
Build Sparse Matrix for Variations in VM Images for use in Offers

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#67]
We need to arrive at the sensible combinations of the following dimensions and then prioritize the order in which the engineering work proceeds on creating these images.

Oracle Linux Version: 7.3, 7.4, 7.6, 8
WLS Version: 12.2.1.2, 12.2.1.3, 12.2.1.4, 14
Java Version: 8 and 11 (only for WLS 14)

A partial, but prioritized list includes:

1. 7.3, 12.2.1.3, 8
2. 7.4, 12.2.1.3, 8
3. 8, 14, 11
4. 8, 14, 8
5. 8, 12.2.1.2, 8

But we need to fill out more.

**Comment by galiacheng** [comment]
Version number of Java 11: 11.0.7, use 1107 to express this version.
WebLogic 14.1.1.0: https://docs.oracle.com/en/middleware/standalone/weblogic-server/14.1.1.0/index.html
Matrix for prioritized one:
"owls-122130-8u131-ol73"
"owls-122130-8u131-ol74"
"owls-141100-1107-ol80"
"owls-141100-8u131-ol80"
"owls-122120-8u131-ol80"

**Comment by galiacheng** [comment]
Sparse matrix is available from https://galiacheng.github.io/wlsimagesku.html.

**Comment by edburns** [comment]
In Progress: 
* 12.2.1.4.0 JDK8u251, 7.6
* 14.1.1 with JDK 8251 and JDK 1107, 7.6
Next
* 12.2.1.2.0 JDKhu251, 7.6

**Comment by edburns** [comment]
<img width="987" alt="image" src="https://user-images.githubusercontent.com/75821/81851892-2c23de00-9528-11ea-9845-9ca2d726bcfe.png">
