### ISSUE TITLE
Publish admin offer with DB and AAD connection

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#68]
Publish as 1.0.17.

**Comment by edburns** [comment]
[arm-oraclelinux-wls-admin-1.0.17-arm-assembly.zip](https://github.com/wls-eng/arm-oraclelinux-wls/files/4582826/arm-oraclelinux-wls-admin-1.0.17-arm-assembly.zip)

**Comment by jacobt123** [comment]
Published to Partner Center

**Comment by edburns** [comment]
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/75821/81855462-617efa80-952d-11ea-96e6-d3e172c6fcac.png">

**Comment by edburns** [comment]
Publish zip from https://github.com/wls-eng/arm-oraclelinux-wls-admin/actions/runs/137703410 .
