### ISSUE TITLE
Publish configured cluster offer with AAG, AAD, and DB

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#69]
Publish as 1.0.23.

**Comment by edburns** [comment]
[arm-oraclelinux-wls-cluster-1.0.23-arm-assembly.zip](https://github.com/wls-eng/arm-oraclelinux-wls/files/4571281/arm-oraclelinux-wls-cluster-1.0.23-arm-assembly.zip)

**Comment by edburns** [comment]
[arm-oraclelinux-wls-cluster-1.0.23-arm-assembly.zip](https://github.com/wls-eng/arm-oraclelinux-wls/files/4582879/arm-oraclelinux-wls-cluster-1.0.23-arm-assembly.zip)

**Comment by edburns** [comment]
[arm-oraclelinux-wls-cluster-1.0.24-arm-assembly.zip](https://github.com/wls-eng/arm-oraclelinux-wls/files/4582895/arm-oraclelinux-wls-cluster-1.0.24-arm-assembly.zip)

**Comment by jacobt123** [comment]
Published on Partner Center

**Comment by edburns** [comment]
[arm-oraclelinux-wls-cluster-1.0.250000-arm-assembly.zip](https://github.com/wls-eng/arm-oraclelinux-wls/files/4583302/arm-oraclelinux-wls-cluster-1.0.250000-arm-assembly.zip)

Fix defaultValue problems found in acceptance testing.

**Comment by jacobt123** [comment]
Published on Partner Center

**Comment by edburns** [comment]
@jacobt123 I found another problem with the Configured Cluster offer: it was using the database pids from the dynamic cluster offer because there were no pids for the configured cluster database offer.

I fixed this in https://github.com/wls-eng/arm-oraclelinux-wls/issues/76 and the result is baked into 1.0.27 at https://github.com/wls-eng/arm-oraclelinux-wls-cluster/actions/runs/101885802 .  Can you please update the configured cluster offer with 1.0.270000 zip?

**Comment by edburns** [comment]
Use zip from https://github.com/wls-eng/arm-oraclelinux-wls-cluster/actions/runs/137861535 .

**Comment by edburns** [comment]
Please use Microsoft.Compute.UserNameTextBox. It comes with built-in validation for Windows and Linux user names

https://solutiontemplates.visualstudio.com/marketplacesolutions/_git/oracle/pullrequest/7661

Same as the other PR(7661), change all of user names to Microsoft.Compute.UserNameTextBox

https://solutiontemplates.visualstudio.com/marketplacesolutions/_git/oracle/pullrequest/7659

**Comment by edburns** [comment]
https://solutiontemplates.visualstudio.com//marketplacesolutions/_git/oracle/pullrequest/7660
