### ISSUE TITLE
App Gateway rule requires trailing slash.  Remove this requirement.

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#74]
# Steps to Reproduce

1. Deploy the cluster with app gateway
2. Deploy a sample app
3. Visit the sample app, but without a trailing slash.  Note that it redirects to a cluster node directly, but with the vm name.
4. Visit the sample app with a trailing slash.  Note that it does not redirect.

> curl --head --verbose http://wlsgw4a56be-weblogic-cafe-group-reza-wlsd.eastus.cloudapp.azure.com/weblogic-cafe
> *   Trying 52.188.77.178...
> * TCP_NODELAY set
> * Connected to wlsgw4a56be-weblogic-cafe-group-reza-wlsd.eastus.cloudapp.azure.com (52.188.77.178) port 80 (#0)
> > HEAD /weblogic-cafe HTTP/1.1
> > Host: wlsgw4a56be-weblogic-cafe-group-reza-wlsd.eastus.cloudapp.azure.com
> > User-Agent: curl/7.58.0
> > Accept: */*
> > 
> < HTTP/1.1 302 Moved Temporarily
> HTTP/1.1 302 Moved Temporarily
> < Date: Wed, 06 May 2020 19:13:53 GMT
> Date: Wed, 06 May 2020 19:13:53 GMT
> < Content-Type: text/html
> Content-Type: text/html
> < Connection: keep-alive
> Connection: keep-alive
> < Set-Cookie: ApplicationGatewayAffinity=21554b2eb568dba34d030034297eb452; Path=/
> Set-Cookie: ApplicationGatewayAffinity=21554b2eb568dba34d030034297eb452; Path=/
> < Location: http://mspVM2:8001/weblogic-cafe/
> Location: http://mspVM2:8001/weblogic-cafe/
> 
> < 
> * Connection #0 to host wlsgw4a56be-weblogic-cafe-group-reza-wlsd.eastus.cloudapp.azure.com left intact
> 
> ~/workareas/weblogic-on-azure$ curl --head --verbose http://wlsgw4a56be-weblogic-cafe-group-reza-wlsd.eastus.cloudapp.azure.com/weblogic-cafe/
> *   Trying 52.188.77.178...
> * TCP_NODELAY set
> * Connected to wlsgw4a56be-weblogic-cafe-group-reza-wlsd.eastus.cloudapp.azure.com (52.188.77.178) port 80 (#0)
> > HEAD /weblogic-cafe/ HTTP/1.1
> > Host: wlsgw4a56be-weblogic-cafe-group-reza-wlsd.eastus.cloudapp.azure.com
> > User-Agent: curl/7.58.0
> > Accept: */*
> > 
> < HTTP/1.1 200 OK
> HTTP/1.1 200 OK
> < Date: Wed, 06 May 2020 19:14:39 GMT
> Date: Wed, 06 May 2020 19:14:39 GMT
> < Content-Type: text/html; charset=UTF-8
> Content-Type: text/html; charset=UTF-8
> < Connection: keep-alive
> Connection: keep-alive
> < Set-Cookie: ApplicationGatewayAffinity=87a187c991cdf614b82980abcbd81713; Path=/
> Set-Cookie: ApplicationGatewayAffinity=87a187c991cdf614b82980abcbd81713; Path=/
> < Set-Cookie: JSESSIONID=sVnraU9YuSKKElBzNbMk4-bGYh6AxUb0sLo27ZF7O-azJx96ZYcB!-27357165; path=/; HttpOnly
> Set-Cookie: JSESSIONID=sVnraU9YuSKKElBzNbMk4-bGYh6AxUb0sLo27ZF7O-azJx96ZYcB!-27357165; path=/; HttpOnly
> 
> < 
> * Connection #0 to host wlsgw4a56be-weblogic-cafe-group-reza-wlsd.eastus.cloudapp.azure.com left intact

**Comment by edburns** [comment]
In my particular situation, I have learned that the solution is best effected in the WebLogic Server configuration.

1. Visit the WLS Console
2. Click "Lock & Edit"
3. Click "Clusters"
4. Click "cluster1"
5. Click "HTTP"
6. Set the "Frontend Host", "Frontend HTTP Port" and "Frontend HTTPS Port" to be the AppGW Public IP, 80, and 443, respectively.
7. Release the configuration.
8. Restart the worker nodes in the cluster.

**Comment by gnsuryan** [comment]
The issue has been fixed and commited to the master branch.

I have tested it for both the scenarios:
enableAppGateway=true & enableAppGateway=false

The changes made can be seen in the below link
:
https://github.com/wls-eng/arm-oraclelinux-wls-cluster/commit/2976907dfec137ba0a77d2d4f35455e895fba969
