### ISSUE TITLE
ol 7.6 network trouble

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#88]
Reproduce steps:
Deploy admin offer from preview link, choose image WebLogic Server 14.1.1.0.0 and JDK 11_07 on Oracle Linux 7.6.  It's ready in resource group "oraclevm-admin-76" in "Oracle Enterprise Java" for quick check.
 Access WebLogic console portal from browser with public ip or dns, e.g. http://wls-d315056581-admindomain.eastus.cloudapp.azure.com:7001/console
Expected result: open WebLogic login page. Actual result: console portal is not accessible.
ssh to adminVM machine and curl http://localhost:7001/console, it works.
WebLogic Server is not available from public access.
 Reproduced images: 
WebLogic Server 14.1.1.0.0 and JDK 11_07 on Oracle Linux 7.6
WebLogic Server 14.1.1.0.0 and JDK 8u251 on Oracle Linux 7.6
WebLogic Server 12.2.1.4.0 and JDK 8u251 on Oracle Linux 7.6
 The issue CANNOT reproduce on images:
WebLogic Server 12.2.1.3.0 and JDK8u131 on Oracle Linux 7.4
WebLogic Server 12.2.1.3.0 and JDK8u131 on Oracle Linux 7.3
Root cause:
 Check with firewall-cmd, no port is open, see screenshot.
Image

Check with netstat
Image

Workaround:
Open port 7001 and 7002 from firewall, can solve the issue, with following commands:
firewall-cmd --zone=public --add-port=7001/tcp --permanent;
firewall-cmd --zone=public --add-port=7002/tcp --permanent;​
firewall-cmd --reload;

More:
I deploy machine with image WebLogic Server 14.1.1.0.0 and JDK 11_07 on Oracle Linux 7.6, ssh to the machine, I found `firewall-cmd` was not available.
Then run setupAdminDomain.sh in that machine, `firewall-cmd` has been installed.
Now WebLogic deploy tool version is 1.8.1, I checked source code, didn't found anything related to firewall.

**Comment by edburns** [comment]
![image](https://user-images.githubusercontent.com/75821/82479135-f76fd380-9a9f-11ea-9a69-4b45f2db86f1.png)

**Comment by edburns** [comment]
![image](https://user-images.githubusercontent.com/75821/82479163-ffc80e80-9a9f-11ea-8753-8b0a6ae7b947.png)

**Comment by galiacheng** [comment]
@sanjaymantoor @edburns 
I fixed the issue for admin offer @[pullrequest](https://github.com/wls-eng/arm-oraclelinux-wls-admin/pull/32), according Sanjay's changes on [arm-oraclelinux-7.6-wls-cluster](https://github.com/wls-eng/arm-oraclelinux-7.6-wls-cluster/blob/master/arm-oraclelinux-wls-cluster/src/main/scripts/setupClusterDomain.sh),  pls review.

**Comment by edburns** [comment]
Resolved in admin and configured cluster offers.  Fix in dynamic cluster still forthcoming from @galiacheng .
