### ISSUE TITLE
Resolve CI/CD problem on configured cluster offer

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#94]
https://github.com/wls-eng/arm-oraclelinux-wls-cluster/runs/714022590

**Comment by galiacheng** [comment]
I got detail error:
DEBUG: msrest.http_logger : ***"error":***"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template parameters 'acceptOTNLicenseAgreement, otnAccountUsername, otnAccountPassword' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are '_artifactsLocation, _artifactsLocationSasToken, aadsPortNumber, aadsPublicIP, aadsServerHost, adminPasswordOrKey, adminUsername, adminVMName, databaseType, dbPassword, dbUser, dsConnectionURL, dnsLabelPrefix, dnsNameforApplicationGateway, enableAAD, enableAppGateway, enableDB, gatewayPublicIPAddressName, jdbcDataSourceName, keyVaultName, keyVaultResourceGroup, keyVaultSSLCertDataSecretName, keyVaultSSLCertPasswordSecretName, linuxImageOfferSKU, linuxImageVersion, location, managedServerPrefix, numberOfInstances, portsToExpose, usePreviewImage, vmSizeSelect, wlsDomainName, wlsLDAPGroupBaseDN, wlsLDAPPrincipal, wlsLDAPPrincipalPassword, wlsLDAPProviderName, wlsLDAPSSLCertificate, wlsLDAPUserBaseDN, wlsUserName, wlsPassword'. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'.","additionalInfo":[***"type":"TemplateViolation","info":***"lineNumber":0,"linePosition":0,"path":""***]***
166
DEBUG: msrest.exceptions : Unable to deserialize to object: type, KeyError: 'TypedErrorInfo'
167
DEBUG: msrest.exceptions : Operation failed with status: 'Bad Request'. Details: 400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/685ba005-af8d-4b04-8f16-a7bf38b2eb5a/resourcegroups/wls-117525401-54/providers/Microsoft.Resources/deployments/wls-cluster-node?api-version=2018-05-01
168
ERROR: cli.azure.cli.core.util : 400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/685ba005-af8d-4b04-8f16-a7bf38b2eb5a/resourcegroups/wls-117525401-54/providers/Microsoft.Resources/deployments/wls-cluster-node?api-version=2018-05-01
169
ERROR: 400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/685ba005-af8d-4b04-8f16-a7bf38b2eb5a/resourcegroups/wls-117525401-54/providers/Microsoft.Resources/deployments/wls-cluster-node?api-version=2018-05-01

We removed OTN parameters in develop branch, we should apply Sanjay's changes in master branch...

**Comment by galiacheng** [comment]
@sanjaymantoor  Hello Sanjay, it's very helpful to use `--debug` for azure cli error details.

**Comment by galiacheng** [comment]
We have to deploy develop branch to Oracle Enterprise Java subscription, otherwise, will get error:
```
"message": "Offer with PublisherId: oracle, OfferId: weblogic-141100-jdk11_07-ol76-preview cannot be purchased due to validation errors. See details for more information.[***\"Legal terms have not been accepted for this item on this subscription: '685ba005-af8d-4b04-8f16-a7bf38b2eb5a'. To accept legal terms using PowerShell, please use Get-AzureRmMarketplaceTerms and Set-AzureRmMarketplaceTerms API(https://go.microsoft.com/fwlink/?linkid=862451), to accept the terms using Azure CLI, please use az vm image accept-terms (https://go.microsoft.com/fwlink/?linkid=2110637) or deploy via the Azure portal to accept the terms\":\"StoreApi\"***]
```

**Comment by galiacheng** [comment]
@sanjaymantoor  Hello Sanjay, I am applying your changes to [cluster/develop branch](https://github.com/galiacheng/arm-oraclelinux-wls-cluster/tree/develop).

**Comment by galiacheng** [comment]
@sanjaymantoor  please feel free to create a PR to master branch for your exsting changes and ask Ed to review, thank you.

**Comment by galiacheng** [comment]
@edburns  @sanjaymantoor  I created [pr 47](https://github.com/wls-eng/arm-oraclelinux-wls-cluster/pull/47) to support running the validation jobs on images owls-122130-8u131-ol74, owls-122140-8u251-ol76, based on Sanjay's existing work, please review.
@sanjaymantoor I didn't include test/scripts/verify-wls-access.sh and test/scripts/verify-servers-lifecycle.sh, I found you are still working on them.

**Comment by sanjaymantoor** [comment]
@galiacheng I am hoping my changes similar to here https://github.com/sanjaymantoor/arm-oraclelinux-wls-cluster/tree/develop  are merged in wls-eng/develop branch.
Currently verify-wls-access and verify-servers-lifecycle verification is showing some inconsistencies with latest develop branch. I am working on it.
With respect to PR to master branch, do I need to initiate pull request on master branch once  [pr 47](https://github.com/wls-eng/arm-oraclelinux-wls-cluster/pull/47)  is merged to wls-eng/develop branch?

**Comment by sanjaymantoor** [comment]
Earlier secret USER_NAME was configured with git login user name. But I checked recent update made , it was used for to form generic git branch as well, which is good. I updated USER_NAME to the git branch user name "wls-eng". After that I am seeing CI/CD went fine.
Refer https://github.com/wls-eng/arm-oraclelinux-wls-cluster/runs/722711505

**Comment by galiacheng** [comment]
> @galiacheng I am hoping my changes similar to here https://github.com/sanjaymantoor/arm-oraclelinux-wls-cluster/tree/develop  are merged in wls-eng/develop branch.
> Currently verify-wls-access and verify-servers-lifecycle verification is showing some inconsistencies with latest develop branch. I am working on it.
> With respect to PR to master branch, do I need to initiate pull request on master branch once  pr 47  is merged to wls-eng/develop branch?

Hello @sanjaymantoor  Please feel free to create a pull request for your changes, I will update my repo after the PR is merged. Thank you

**Comment by sanjaymantoor** [comment]
Updated Verify WebLogic Server Access and Verify WebLogic Managed Server LifeCycle check.
Refer https://github.com/wls-eng/arm-oraclelinux-wls-cluster/pull/49
